### ISSUE TITLE
SFZ Build v1.2.2 source code file is broken

### ISSUE THREAD

**Issue by lucmp** [sgossner/VCSL#25]
SFZ Build v1.2.2 source code ZIP file is broken
 and is impossible to download. Please see screenshot.

![broken-download](https://user-images.githubusercontent.com/2882969/52423074-8260d080-2ade-11e9-9450-291184b6e79f.png)

**Comment by lucmp** [comment]
I just tried the tar.gz file and it fails too. Is there a 2GB limit set by Github?

**Comment by sgossner** [comment]
Have you tried downloading via the 'Clone or Download' button on the branch page?
https://github.com/sgossner/VCSL/tree/sfz

I don't think there is any limit on the size, but one can't be sure about these sorts of things anymore. It is possible the .zip became corrupted somehow; it was automatically created by GitHub, so I don't know exactly how it was created or if GitHub's system has issues with large files or something. 

Seeing the issue being so consistent, I would be led to think that the problem is with the file, so I'll check it when I get back to the studio.

**Comment by peastman** [comment]
If it's a problem with the file, we can file a help ticket with GitHub.

**Comment by A6111** [comment]
File is still broken. Is there another possibility to download this?

**Comment by peastman** [comment]
You can always get the repository with git:

```
git clone https://github.com/sgossner/VCSL.git
git checkout sfz
```

**Comment by Inversil** [comment]
yea, I'm still having trouble downloading the soundfonts..

**Comment by sgossner** [comment]
I have now added an official mirror on Dropbox for this build for those who are having difficulties, as a last resort.
