### ISSUE TITLE
The tar.gz and zip downloads in the releases page are broken

### ISSUE THREAD

**Issue by heretoenhance** [sgossner/VCSL#26]
Maybe this repo has been abandoned forever but I'm reporting anyway for anyone who might read.

As I said in the title, both the downloads in the releases page are broken, they both download a file that is 1GB but trying to extract them gives an error, they are probably truncated.

The dropbox link thankfully works.

**Comment by sgossner** [comment]
Not abandoned, just working on new commercial projects at the moment, and current events have put a damper on recording new instruments in general. :)

I was not able to replicate your error; I had no trouble downloading past 1 GB just now. Maybe it is truncated for people who are not contributors to the project? In either case, there's nothing I can do to fix this as it's Github's problem as Github generated the .zip files, hence why I upload the mirror.

One thing I might do is convert the entire library to FLAC. It's lossless, but compressed so it'll save about 50-90% of the space when downloading, considerably better than ZIP. The disadvantage of course is FLAC is less accessible to people, so any thoughts on this are welcome!

**Comment by heretoenhance** [comment]
I see, sorry for implying the repo was abandoned.

Flac might be a good idea but I am not an expert in sfz players, do they support it? If at least sfizz and Sforzando support it then there would be only advantages in converting the library to it.

**Comment by sgossner** [comment]
No worries!

Sforzando supports FLAC, and as far as I know Sfizz supports it too. If I recall, FLAC and OGG support are in the original SFZ spec, so most players are supposed to support them.

The main disadvantage is still many computers don't have default audio players which can open FLAC files, and some users may not know how to open and edit FLAC files otherwise, while with WAV, pretty much everyone knows what PCM WAV audio is.

**Comment by peastman** [comment]
I suspect that anyone who's into editing musical instrument samples is someone who will have no trouble dealing with FLAC files!

**Comment by heretoenhance** [comment]
I agree with @peastman. And if it's true that Flac is in the SFZ specs there's no reason not to use it while distributing libraries. Still I don't know if compressing everything to flac and then compressing it again with tar.xz or tar.gz or zip would suffice in making it under 1GB. Maybe splitting it in two?

**Comment by sgossner** [comment]
FLAC is superior to tar.gz/.zip in compression of audio data (since it is designed specifically for PCM audio), so these compressed formats will not reduce the size any more after FLAC, unlike WAV where ZIP and especially RAR and other more modern compression formats can be very successful.

The only way to reduce size further would be to either reduce parameters (lower bit depth, sample rate, reduce sample count, or cut samples shorter), or to use lossy format like OGG Vorbis.

**Comment by heretoenhance** [comment]
Yes I know, that's why I said that it wouldn't be enough.

Since many people, including me, are using this library for audio production, I believe lossless is the only way to go. Having the best quality allows to process and work with sound without degrading it too much.

So I suggest you compress everything to flac and replace the github download link with smaller downloads (under 1GB) to prevent the truncation I described when opening the issue.

**Comment by sgossner** [comment]
> So I suggest you compress everything to flac, if you can, and replace the github download link with smaller downloads (under 1GB) to prevent the truncation I described when opening the issue.
> 
> Thank you, really appreciate your work.

I'll probably just encourage people to use the Dropbox mirror, or mirror it directly on the Versilian Studios file server with the next version. That way I'm not reliant on Github or anyone else for distributing the file.

Thanks for your input!
