### ISSUE TITLE
Do you really need to download everything twice?

### ISSUE THREAD

**Issue by squinkylabs** [sgossner/VCSL#28]
It seems cloning the repo pulls down many gigs of samples, but no SFZ files. To get the SFZ files you need to download a release thart contains...... all of those samples again!

If the recommended way of consuming the library is with though git (for ease of update), I guess that means I do a git clone, then download the release, unzip it, manually copy the SFZ files into my git repo, then delete the downloaded release?

Or am I missing something obvious here?

**Comment by sgossner** [comment]
Do a git clone of the 'sfz' branch and sync that down, not the 'master' branch. 'Master' is where all the plain .wav files live for anyone seeking to use the library to build their own patches; 'sfz' is where the official SFZ conversion of the library lives.

**Comment by squinkylabs** [comment]
ah! thanks. You might consider updating the main readme.

**Comment by peastman** [comment]
When you clone the repository, you get all the branches.  Once you've done that, you can type

```
git checkout sfz
```

to switch branches, and the files will appear.

**Comment by squinkylabs** [comment]
Oh, yes, of course it works like a charm. I just meant that not everyone will think to checkout a different branch. so if you updated the readme it might be easier for people.

**Comment by sgossner** [comment]
Thanks, but the readme already very clearly directs people to go to this page to download the SFZ version:
https://github.com/sgossner/VCSL/releases/

Most people don't want/need to clone the repo, they just want the files. Releases provides the desired files ready to go in a single .zip.

VCSL is intended as a raw sound library first and foremost, not a SFZ library. The SFZ implementation is a polite, open source example implementation to show people working from the samples how they might go about using or mapping them, and to allow end users to explore the instruments in situations where no one has made a fancier version yet.

That's why the SFZ version is on a separate branch, and not the main one.
