### ISSUE TITLE
No included converter or SFZ files

### ISSUE THREAD

**Issue by Nick-Hope** [sgossner/VCSL#30]
Thank you for generously making these samples freely available.

The README.md file says:

_Huge thanks to Peter Eastman for creating a fantastic Python utility that auto-generates SFZ files- it's included as CC0 as part of the download!_

I could not find any such utility in the download. If it is not included, perhaps that text could be taken out of the description, to avoid confusion. I believe that the utility is actually available at https://vis.versilstudios.com/assets/pe_sfzpythonautomapper_5-12-2019.zip, and that an alternative folder-to-sf converter is at https://vis.versilstudios.com/sfzconverter.html

Further to that, "SFZ Version" implied to me that there would be included SFZ files. However I found none. If these are just WAV samples, and the user is expected to create their own SFZ files for the samples, perhaps that could be made clearer in the description.

**Comment by sgossner** [comment]
The SFZ files and utility are found on the SFZ branch:
https://github.com/sgossner/VCSL/tree/sfz

You should download the Repository using the release, which is specifically of the SFZ branch, as noted in the Readme:
https://github.com/sgossner/VCSL/releases/

The release is also mirrored there on Dropbox in case you have download issues from GitHub (not uncommon sadly).

If using GitHub Desktop to download the library, sync the SFZ branch instead of the Main branch. That will give you the SFZ files and python automapper. Sometimes people sync the Main branch, don't see the SFZ files, and don't realize there's a separate SFZ branch which can be confusing.

The reason this is done is because VCSL is technically just the sampleset itself, the SFZ files are an add-on created afterwards and separately maintained, so they live in a separate branch. Similarly if someone made a DecentSampler or Kontakt version, it could be organized in the same way. This lets us work on the sampleset itself, then pull those changes over to the SFZ version as needed.

The Python automapper is not for the faint of heart. You should only use it if you are experienced with Python and the command line, and I cannot provide any support or assistance with it. Folder to SFZ is much simpler (has a GUI) and easier to use with a full video tutorial series, but has somewhat less features; however I can provide support with it if you run into issues.

**Comment by Nick-Hope** [comment]
Thank you. I now have a download with the SFZ files. Github often confuses me so I found it difficult navigating to the SFZ branch. Perhaps it would be easier if the link in the "SFZ Version" section of the readme pointed to https://github.com/sgossner/VCSL/tree/sfz and not to https://github.com/sgossner/VCSL/releases/? It's possible I'm being thick :)

**Comment by sgossner** [comment]
> Thank you. I now have a download with the SFZ files. Github often confuses me so I found it difficult navigating to the SFZ branch. Perhaps it would be easier if the link in the "SFZ Version" section of the readme pointed to https://github.com/sgossner/VCSL/tree/sfz and not to https://github.com/sgossner/VCSL/releases/? It's possible I'm being thick :)

Downloading the SFZ branch directly is not recommended as it seems GitHub dynamically has to zip up the entire thing before letting you download, which is prone to failures at this size. Releases instead provides a more reliable and streamlined download experience since the files are pre-zipped and ready to download, and we can easily link to the Dropbox mirror for those experiencing difficulties.

The actual process of dealing with branches and GitHub itself is more for people who want to develop stuff based on VCSL, while the Releases section is for composers/producers who just want to use the sounds.

**Comment by Nick-Hope** [comment]
It looks like GitHub's zip from the SFZ branch has worked OK. The samples seem the same as those from Releases. I think you can close this again now. Thanks very much Sam.
